// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSgI-y6JXWLRBdM6zW4PADiiLSRDR7_pw',
    appId: '1:891923254984:web:33864bb2bffd0e45a99ffd',
    messagingSenderId: '891923254984',
    projectId: 'messaging-app-4670c',
    authDomain: 'messaging-app-4670c.firebaseapp.com',
    storageBucket: 'messaging-app-4670c.firebasestorage.app',
    measurementId: 'G-291KTMNT5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvp_1_D0EECZWTxNWaK7Tvo0FHgFYOMtE',
    appId: '1:891923254984:android:d25972357ac3e99ba99ffd',
    messagingSenderId: '891923254984',
    projectId: 'messaging-app-4670c',
    storageBucket: 'messaging-app-4670c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXUbLV_O-uka2mw4PqSMkvM5wk4SExmU',
    appId: '1:891923254984:ios:da53074651fdcf1ba99ffd',
    messagingSenderId: '891923254984',
    projectId: 'messaging-app-4670c',
    storageBucket: 'messaging-app-4670c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvXUbLV_O-uka2mw4PqSMkvM5wk4SExmU',
    appId: '1:891923254984:ios:da53074651fdcf1ba99ffd',
    messagingSenderId: '891923254984',
    projectId: 'messaging-app-4670c',
    storageBucket: 'messaging-app-4670c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSgI-y6JXWLRBdM6zW4PADiiLSRDR7_pw',
    appId: '1:891923254984:web:3064a6140be2bddda99ffd',
    messagingSenderId: '891923254984',
    projectId: 'messaging-app-4670c',
    authDomain: 'messaging-app-4670c.firebaseapp.com',
    storageBucket: 'messaging-app-4670c.firebasestorage.app',
    measurementId: 'G-JH03YZKJZ9',
  );
}
